
name: 'Gradle build action'
description: 'Running gradle build and cache the results'
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: .
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      
    - name: build gradle
      if: steps.cache.outputs.cache-hit != 'true'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      
