name: Windows build

on: [push, pull_request]

jobs:
  build-win:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019, windows-2016]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install VC-Redist 2012
      run: |
        Install-Module -Name VcRedist -Force
        $VcList = Get-VcList -Release "2012"
        Save-VcRedist -VcList $VcList
        Install-VcRedist -VcList $VcList -Silent
    - name: Build with Gradle
      run: .\gradlew.bat build
