name: Create release file
'on':
  workflow_dispatch: null
jobs:
  # calling_build_workflow:
  #  uses: blagazsolt/theta/.github/workflows/test-build.yml@master
    
  gradle:
   # needs: calling_build_workflow
    name: Run Gradle
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/workflows/action
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: build --scan
      - run: 'echo "${{steps.build.outputs.build}}"'
      - uses: actions/upload-artifact@v3
        with:
          name: ThetaJars
          path: subprojects/**/*-all.jar
  publish:
    name: Publish Release
    needs: gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creating version number
        run: >-
          echo "version=$(grep "version" build.gradle.kts | tail -n 1 | cut -d
          "=" -f2 | xargs echo )" >> $GITHUB_OUTPUT
        id: value
        shell: bash
      - run: 'echo "${{steps.value.outputs.version}}"'
      - uses: actions/download-artifact@v3
        with:
          name: ThetaJars
          path: jar/
      - name: Display structure of downloaded files
        run: ls -R
      - run: find jar
      - run: for i in $(find jar -name "*-all.jar"); do mv $i jar/$(basename ${i%-${{steps.value.outputs.version}}-all.jar}.jar); done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: jar/**/*.jar
          body: "Auto-generated release"
          name: ${{steps.value.outputs.version}}
          tag_name: ${{steps.value.outputs.version}}
         
